-- MySQL Script generated by MySQL Workbench
-- Thu May  5 18:10:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mycafe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mycafe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mycafe` DEFAULT CHARACTER SET utf8 ;
USE `mycafe` ;

-- -----------------------------------------------------
-- Table `mycafe`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycafe`.`Customers` (
  `name` VARCHAR(50) NULL,
  `address` VARCHAR(50) NULL,
  `city` VARCHAR(50) NULL,
  `email` CHAR(255) NULL,
  `id` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycafe`.`Waiters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycafe`.`Waiters` (
  `id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `workerid` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycafe`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycafe`.`Orders` (
  `num` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME(3) NOT NULL,
  `waitid` VARCHAR(10) NOT NULL,
  `custid` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`num`),
  INDEX `wait_id_idx` (`waitid` ASC) VISIBLE,
  INDEX `custid_idx` (`custid` ASC) VISIBLE,
  CONSTRAINT `waitid`
    FOREIGN KEY (`waitid`)
    REFERENCES `mycafe`.`Waiters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `custid`
    FOREIGN KEY (`custid`)
    REFERENCES `mycafe`.`Customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycafe`.`Vendors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycafe`.`Vendors` (
  `id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `address` VARCHAR(50) NULL,
  `vend_city` VARCHAR(50) NULL,
  `area` VARCHAR(50) NULL,
  `post` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycafe`.`Cafe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycafe`.`Cafe` (
  `id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `site` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycafe`.`Structure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycafe`.`Structure` (
  `id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `place` VARCHAR(50) NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `cafeid` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cafeid_idx` (`cafeid` ASC) VISIBLE,
  CONSTRAINT `cafeid`
    FOREIGN KEY (`cafeid`)
    REFERENCES `mycafe`.`Cafe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycafe`.`Positions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycafe`.`Positions` (
  `id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `salary` DECIMAL(8,2) NOT NULL,
  `departid` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `departid_idx` (`departid` ASC) VISIBLE,
  CONSTRAINT `departid`
    FOREIGN KEY (`departid`)
    REFERENCES `mycafe`.`Structure` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycafe`.`Workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycafe`.`Workers` (
  `id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `surname` VARCHAR(50) NOT NULL,
  `address` VARCHAR(50) NULL,
  `city` VARCHAR(50) NULL,
  `email` VARCHAR(255) NULL,
  `posid` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `posid_idx` (`posid` ASC) VISIBLE,
  CONSTRAINT `posid`
    FOREIGN KEY (`posid`)
    REFERENCES `mycafe`.`Positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycafe`.`Cookers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycafe`.`Cookers` (
  `id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `workerid` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `workerid_idx` (`workerid` ASC) VISIBLE,
  CONSTRAINT `workerid`
    FOREIGN KEY (`workerid`)
    REFERENCES `mycafe`.`Workers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycafe`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycafe`.`Products` (
  `id` VARCHAR(10) NOT NULL,
  `vendid` VARCHAR(10) NOT NULL,
  `cookerid` VARCHAR(10) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `price` DECIMAL(8,2) NOT NULL,
  `desc` TEXT(500) NULL,
  PRIMARY KEY (`id`),
  INDEX `vendid_idx` (`vendid` ASC) VISIBLE,
  INDEX `cookerid_idx` (`cookerid` ASC) VISIBLE,
  CONSTRAINT `vendid`
    FOREIGN KEY (`vendid`)
    REFERENCES `mycafe`.`Vendors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cookerid`
    FOREIGN KEY (`cookerid`)
    REFERENCES `mycafe`.`Cookers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycafe`.`OrderItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycafe`.`OrderItems` (
  `num` INT NOT NULL,
  `item` INT NOT NULL,
  `prodid` VARCHAR(10) NOT NULL,
  `quantity` INT NOT NULL,
  `itemprice` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`num`, `item`),
  INDEX `prodid_idx` (`prodid` ASC) VISIBLE,
  CONSTRAINT `num`
    FOREIGN KEY (`num`)
    REFERENCES `mycafe`.`Orders` (`num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `prodid`
    FOREIGN KEY (`prodid`)
    REFERENCES `mycafe`.`Products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycafe`.`Expense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycafe`.`Expense` (
  `id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `recipient` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycafe`.`Profit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycafe`.`Profit` (
  `id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `source` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycafe`.`Currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycafe`.`Currency` (
  `id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycafe`.`FinanceOperations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycafe`.`FinanceOperations` (
  `num` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `profid` VARCHAR(10) NOT NULL,
  `expid` VARCHAR(10) NOT NULL,
  `ordernum` INT NOT NULL,
  `volume` DECIMAL(8,2) NOT NULL,
  `currencyid` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`num`),
  INDEX `profid_idx` (`profid` ASC) VISIBLE,
  INDEX `expid_idx` (`expid` ASC) VISIBLE,
  INDEX `currencyid_idx` (`currencyid` ASC) VISIBLE,
  INDEX `ordernum_idx` (`ordernum` ASC) VISIBLE,
  CONSTRAINT `profid`
    FOREIGN KEY (`profid`)
    REFERENCES `mycafe`.`Profit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `expid`
    FOREIGN KEY (`expid`)
    REFERENCES `mycafe`.`Expense` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `currencyid`
    FOREIGN KEY (`currencyid`)
    REFERENCES `mycafe`.`Currency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ordernum`
    FOREIGN KEY (`ordernum`)
    REFERENCES `mycafe`.`Orders` (`num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
